name: Build native binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with: { version: "0.13.0" }

      - name: Install ShaderC
        run: |
          sudo apt-get update
          sudo apt-get install -y glslc

      - name: Build for x86_64 Linux glibc
        run: zig build -Doptimize=ReleaseSafe -Dsuffix -Dstrip -Dtimestamp -Dtarget=x86_64-linux-gnu
      - name: Build for x86_64 Linux musl
        run: zig build -Doptimize=ReleaseSafe -Dsuffix -Dstrip -Dtimestamp -Dtarget=x86_64-linux-musl
      - name: Build for x86_64 Windows
        run: zig build -Doptimize=ReleaseSafe -Dsuffix -Dstrip -Dtimestamp -Dtarget=x86_64-windows

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: zig-out/bin/slimy-*-*
